javax:
    sql:
        DataSource:
            empDataSource:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@localhost:1521/XE
                    user: c##ifms
                    password: password


   
           
